backend:
  name: git-gateway
  branch: main   # если у тебя ветка master — замени на master

media_folder: "images/uploads"   # файлы будут храниться в репозитории
public_folder: "./images/uploads"

site_url: "https://staslavrenchuk.github.io/tiling-site"

collections:
  - name: "services"
    label: "Услуги"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Название", widget: "string" }
      - { name: "price", label: "Цена", widget: "string" }
      - { name: "image", label: "Изображение", widget: "image" }

  - name: "portfolio"
    label: "Портфолио"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Название объекта", widget: "string" }
      - { name: "image", label: "Фото", widget: "image" }

  - name: "about"
    label: "О компании"
    files:
      - file: "content/about.md"
        label: "О компании"
        name: "about"
        fields:
          - { name: "body", label: "Описание", widget: "markdown" }
